import { BRAND_COLORS } from "./colors";

export const theme = {
  light: {
    background: BRAND_COLORS.BACKGROUND,
    foreground: BRAND_COLORS.TEXT,
    card: BRAND_COLORS.BACKGROUND,
    cardForeground: BRAND_COLORS.TEXT,
    popover: BRAND_COLORS.BACKGROUND,
    popoverForeground: BRAND_COLORS.TEXT,
    primary: BRAND_COLORS.PRIMARY,
    primaryForeground: "#ffffff",
    secondary: BRAND_COLORS.PRIMARY_LIGHT,
    secondaryForeground: BRAND_COLORS.PRIMARY,
    muted: "rgba(0, 0, 0, 0.05)",
    mutedForeground: "rgba(0, 0, 0, 0.5)",
    accent: BRAND_COLORS.PRIMARY_LIGHT,
    accentForeground: BRAND_COLORS.PRIMARY,
    destructive: BRAND_COLORS.ERROR,
    destructiveForeground: "#ffffff",
    border: BRAND_COLORS.BORDER,
    input: BRAND_COLORS.BORDER,
    ring: BRAND_COLORS.PRIMARY,
  },
  dark: {
    background: BRAND_COLORS.BACKGROUND_DARK,
    foreground: "#ffffff",
    card: BRAND_COLORS.BACKGROUND_DARK,
    cardForeground: "#ffffff",
    popover: BRAND_COLORS.BACKGROUND_DARK,
    popoverForeground: "#ffffff",
    primary: BRAND_COLORS.PRIMARY,
    primaryForeground: "#ffffff",
    secondary: BRAND_COLORS.PRIMARY_LIGHT,
    secondaryForeground: BRAND_COLORS.PRIMARY,
    muted: "rgba(255, 255, 255, 0.05)",
    mutedForeground: "rgba(255, 255, 255, 0.5)",
    accent: BRAND_COLORS.PRIMARY_LIGHT,
    accentForeground: BRAND_COLORS.PRIMARY,
    destructive: BRAND_COLORS.ERROR,
    destructiveForeground: "#ffffff",
    border: BRAND_COLORS.BORDER,
    input: BRAND_COLORS.BACKGROUND_INPUT,
    ring: BRAND_COLORS.PRIMARY,
  },
} as const;
